/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPatientsRouteImport } from './routes/_app.patients'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAddPatientRouteImport } from './routes/_app.add-patient'
import { Route as SrcRoutesAppAddPatientRouteImport } from './routes/src/routes/_app.add-patient'
import { Route as AppPatientsPatientIdPrescriptionsNewRouteImport } from './routes/_app.patients.$patientId.prescriptions.new'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/_app/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/_app/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/_app/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/_app/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/_app/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAddPatientRoute = AppAddPatientRouteImport.update({
  id: '/_app/add-patient',
  path: '/add-patient',
  getParentRoute: () => rootRouteImport,
} as any)
const SrcRoutesAppAddPatientRoute = SrcRoutesAppAddPatientRouteImport.update({
  id: '/src/routes/_app/add-patient',
  path: '/src/routes/add-patient',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPatientsPatientIdPrescriptionsNewRoute =
  AppPatientsPatientIdPrescriptionsNewRouteImport.update({
    id: '/$patientId/prescriptions/new',
    path: '/$patientId/prescriptions/new',
    getParentRoute: () => AppPatientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/add-patient': typeof AppAddPatientRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/patients': typeof AppPatientsRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/src/routes/add-patient': typeof SrcRoutesAppAddPatientRoute
  '/patients/$patientId/prescriptions/new': typeof AppPatientsPatientIdPrescriptionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/add-patient': typeof AppAddPatientRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/patients': typeof AppPatientsRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/src/routes/add-patient': typeof SrcRoutesAppAddPatientRoute
  '/patients/$patientId/prescriptions/new': typeof AppPatientsPatientIdPrescriptionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_app/add-patient': typeof AppAddPatientRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/patients': typeof AppPatientsRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/src/routes/_app/add-patient': typeof SrcRoutesAppAddPatientRoute
  '/_app/patients/$patientId/prescriptions/new': typeof AppPatientsPatientIdPrescriptionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/add-patient'
    | '/dashboard'
    | '/notifications'
    | '/patients'
    | '/profile'
    | '/settings'
    | '/src/routes/add-patient'
    | '/patients/$patientId/prescriptions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/add-patient'
    | '/dashboard'
    | '/notifications'
    | '/patients'
    | '/profile'
    | '/settings'
    | '/src/routes/add-patient'
    | '/patients/$patientId/prescriptions/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/_app/add-patient'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/patients'
    | '/_app/profile'
    | '/_app/settings'
    | '/src/routes/_app/add-patient'
    | '/_app/patients/$patientId/prescriptions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AppAddPatientRoute: typeof AppAddPatientRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPatientsRoute: typeof AppPatientsRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  SrcRoutesAppAddPatientRoute: typeof SrcRoutesAppAddPatientRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/add-patient': {
      id: '/_app/add-patient'
      path: '/add-patient'
      fullPath: '/add-patient'
      preLoaderRoute: typeof AppAddPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/src/routes/_app/add-patient': {
      id: '/src/routes/_app/add-patient'
      path: '/src/routes/add-patient'
      fullPath: '/src/routes/add-patient'
      preLoaderRoute: typeof SrcRoutesAppAddPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/patients/$patientId/prescriptions/new': {
      id: '/_app/patients/$patientId/prescriptions/new'
      path: '/$patientId/prescriptions/new'
      fullPath: '/patients/$patientId/prescriptions/new'
      preLoaderRoute: typeof AppPatientsPatientIdPrescriptionsNewRouteImport
      parentRoute: typeof AppPatientsRoute
    }
  }
}

interface AppPatientsRouteChildren {
  AppPatientsPatientIdPrescriptionsNewRoute: typeof AppPatientsPatientIdPrescriptionsNewRoute
}

const AppPatientsRouteChildren: AppPatientsRouteChildren = {
  AppPatientsPatientIdPrescriptionsNewRoute:
    AppPatientsPatientIdPrescriptionsNewRoute,
}

const AppPatientsRouteWithChildren = AppPatientsRoute._addFileChildren(
  AppPatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AppAddPatientRoute: AppAddPatientRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPatientsRoute: AppPatientsRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  SrcRoutesAppAddPatientRoute: SrcRoutesAppAddPatientRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
